Page({
	data:{
		person:[
               {
                 index:'姓名',
                 message:''
               },
               {
                 index:'手机',
                 message:''
               },
               {
                 index:'QQ',
                 message:''
               },
               {
                 index:'微信',
                 message:''
               },
               {
                 index:'邮箱',
                 message:''
               },
               {
                 index:'专业',
                 message:''
               },
            ],
            select:[
               {
                  index:'入学年份',
                  message:''     
               },
               {
                  index:'部门',
                  message:''
               },
               {
                  index:'Quanta最高职位',
                  message:''
               }],
            experience:[
            {
                  index:'入职年份',
                  message:''
            },
            {
                  index:'入职公司',
                  message:''
            },
            {
                  index:'就职岗位',
                  message:''
            }]
	}
})