Page({
	data:{
       person:
         {
         	name:'曾泽君',
            office:'12th CEO',
            department:'研发部'
         },
       personDetail:[
         {
         	index:'手机',
         	message:'13232323119'
         },
         {
         	index:'QQ',
         	message:'6100912311'
         },
         {
         	index:'微信',
         	message:'6100912311'
         },
         {
         	index:'邮箱',
         	message:'6100912311'
         },
       ],
       case:[
         {
         	index:'专业',
         	message:'计算机-网络工程'
         },
         {
            index:'入学年份',
            message:'2015'
         },
         {
         	index:'Quanta最高职位',
         	message:'CEO'
         }
       ],
       experience:[
         {
         	year:'2011',
         	office:'腾讯计算机有限公司',
         	position:'后台工程师'
         },
         {
         	year:'2013',
         	office:'网易公司',
         	position:'后台工程师'
         }
       ]
	},
})