Page({
	data:{
		rank:[
               {
                rating:'25%',
                office:'阿里',
                number:25
               },
               {
               	rating:'25%',
               	office:'百度'
               },
               {
               	rating:'20%',
               	office:'腾讯'
               }
		],
		percentGoes:[
               {
               	number:250,
               	office:'其他'
               },
               {
                number:100,
                office:'腾讯',
               },
               {
               	number:100,
               	office:'阿里'
               },
               {
               	number:50,
               	office:'百度'
               }
		]
	}
})